service: aws-lambda-w3w-map-api

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
  region: us-east-1

# Overwrite the default memory size. Default is 1024
  memorySize: 512

plugins:
  - serverless-env-generator
  - serverless-offline

# Plugin config goes into custom:
custom:
  envFiles: #YAML files used to create .env file
    - environment.yml

functions:
  what3wordsMap:
    handler: handler.what3wordsMap
    events:
      - http:
          path: what3words/map
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                addr: false
                coords: false
